services:
  - type: web
    name: cerebro-whatsapp-ia
    runtime: python
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg tesseract-ocr tesseract-ocr-spa
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
